"""empty message

Revision ID: 384b6096c689
Revises: 08a4308b7449
Create Date: 2017-05-06 08:59:30.807966

"""

# revision identifiers, used by Alembic.
revision = '384b6096c689'
down_revision = '08a4308b7449'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('can_have_children', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node', 'can_have_children')
    ### end Alembic commands ###
