"""empty message

Revision ID: 4ad9d252e153
Revises: 384b6096c689
Create Date: 2017-05-06 12:45:25.694949

"""

# revision identifiers, used by Alembic.
revision = '4ad9d252e153'
down_revision = '384b6096c689'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('node_parent_id_fkey', 'node', type_='foreignkey')
    op.create_foreign_key(None, 'node', 'node', ['parent_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'node', type_='foreignkey')
    op.create_foreign_key('node_parent_id_fkey', 'node', 'node', ['parent_id'], ['id'])
    ### end Alembic commands ###
