"""empty message

Revision ID: 5b6693c2ef4c
Revises: None
Create Date: 2017-05-03 09:04:26.254331

"""

# revision identifiers, used by Alembic.
revision = '5b6693c2ef4c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node',
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_parent_id'), 'node', ['parent_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_parent_id'), table_name='node')
    op.drop_table('node')
    ### end Alembic commands ###
