"""empty message

Revision ID: 68d804d54ccf
Revises: 4ad9d252e153
Create Date: 2017-05-06 13:37:52.023083

"""

# revision identifiers, used by Alembic.
revision = '68d804d54ccf'
down_revision = '4ad9d252e153'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('max_num', sa.SmallInteger(), nullable=False))
    op.add_column('node', sa.Column('min_num', sa.SmallInteger(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node', 'min_num')
    op.drop_column('node', 'max_num')
    ### end Alembic commands ###
