"""empty message

Revision ID: c05c7a78e346
Revises: 68d804d54ccf
Create Date: 2017-05-07 12:48:41.203130

"""

# revision identifiers, used by Alembic.
revision = 'c05c7a78e346'
down_revision = '68d804d54ccf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('node', 'max_num',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('node', 'min_num',
               existing_type=sa.SMALLINT(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('node', 'min_num',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('node', 'max_num',
               existing_type=sa.SMALLINT(),
               nullable=False)
    ### end Alembic commands ###
