"""empty message

Revision ID: ebb65d877474
Revises: c05c7a78e346
Create Date: 2017-05-07 19:50:18.363313

"""

# revision identifiers, used by Alembic.
revision = 'ebb65d877474'
down_revision = 'c05c7a78e346'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('node_name_key', 'node', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('node_name_key', 'node', ['name'])
    ### end Alembic commands ###
